# Generated by Django 6.0.2 on 2026-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='availability_reenable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
